---
- name: playbook for simple 1 GB partition
  hosts: all
  become: true
  tasks:
    - name: First Task - Using shell module to check if virtualenv is present or not
      ansible.builtin.shell:
        cmd: uptime
